### ISSUE TITLE
I use the inference code to load ''SQLCoder-7B' ,but an error occur. 

### ISSUE THREAD

**Issue by zhouenxian** [defog-ai/sqlcoder#34]
I use the inference code to load ''SQLCoder-7B' ,but an error occur. Here are traceback information:

Traceback (most recent call last):
File "/datas/work/zex/llm/sqlcoder-7b/spider_sqlcoder_7b.py", line 103, in
model = AutoModelForCausalLM.from_pretrained(
File "/home/linewell/anaconda3/envs/SQLCoder/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 482, in from_pretrained
config, kwargs = AutoConfig.from_pretrained(
File "/home/linewell/anaconda3/envs/SQLCoder/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 1022, in from_pretrained
config_class = CONFIG_MAPPING[config_dict["model_type"]]
File "/home/linewell/anaconda3/envs/SQLCoder/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 723, in getitem
raise KeyError(key)
KeyError: 'mistral'

**Comment by rishsriv** [comment]
Hi there, you'll have to upgrade your `transformers` library to `4.34.0` to use Mistral-7B, which is the base model for SQLCoder-7B

**Comment by zhouenxian** [comment]
I solved this error with your suggestion. Thank you very much
